### ISSUE TITLE
Unresponsive login under Fedora/Linux

### ISSUE THREAD

**Issue by scaramouche88** [Pietrucci-Blacher/notion-snap-reborn#101]
Hi! Thanks A LOT for the fork and the renaissance of this project.

However I'm not able to write in any way in the log-in page - I usually log with email.
Simply unresponsive.
FYI I had the same problem with the older version of the project.

I used the snap version.
Fedora 38
Gnome 44.7
Wayland drivers

Thanks!

**Comment by Pietrucci-Blacher** [comment]
Hi, i was not aware about that issue, that's quite surprising. I'm putting it in my workdraft for the next major release :wink:
