### ISSUE TITLE
No app icon on Kubuntu

### ISSUE THREAD

**Issue by guyluz11** [Pietrucci-Blacher/notion-snap-reborn#28]
I am using the snap on Kubuntu 23.04
When searching for installed apps the icon is correct

![image](https://github.com/Pietrucci-Blacher/notion-snap-reborn/assets/9304740/e7f9a78d-605c-4138-abeb-b0247d893978)

but when the app is open icon is missing

![image](https://github.com/Pietrucci-Blacher/notion-snap-reborn/assets/9304740/1e87dd9a-31cc-4c14-87be-ec491fd33d53)

> Snap name: notion-snap-reborn, version: 1.0.4, Rev 5, Tracking: latest/stable, Publisher:   sunshio

**Comment by Pietrucci-Blacher** [comment]
Tested it on the latest version of Kubuntu 23.10, seems to have no issues, maybe try to reinstall it.

**Comment by Pietrucci-Blacher** [comment]
Seems to be an issue with Electron, I've checked whole linked opened issues, and maybe coming in the next patches
