### ISSUE TITLE
Notion Tabs

### ISSUE THREAD

**Issue by taiporto** [Pietrucci-Blacher/notion-snap-reborn#46]
Hey! That's a great repackaging of the old notion-snap, thank you so much for your work!

I saw that Notion recently rolled out a new feature: tabs on the desktop app. Is this something that could possibly be included in your snap package?

**Comment by Pietrucci-Blacher** [comment]
Hello, I don't really have control over the updates Notion makes to their product but I think this may come back as the community/users aren't really happy with this sudden change.
