### ISSUE TITLE
Spellcheck still enabled

### ISSUE THREAD

**Issue by LoryPack** [Pietrucci-Blacher/notion-snap-reborn#74]
Hello, thanks a lot for this useful package. 

On my machine, unfortunately, the spellcheck is still enabled even if I found a commit that seemed to disable it. I installed using `snap install notion-snap-reborn` and I am on Ubuntu 20.04. Do you know how to fix that?

**Comment by Pietrucci-Blacher** [comment]
Hello, I've been quite occupied with my studies, but I can confirm that I tried to reproduce the issue on my own computer (Ubuntu 20.04) and haven't observed any problems related to spellcheck since I applied the previous patch. For now, I'm closing the issue and will reopen it if any issues arise.
