### ISSUE TITLE
Web links opening in Electron instead of external browsers

### ISSUE THREAD

**Issue by LoryPack** [Pietrucci-Blacher/notion-snap-reborn#75]
If I click on a link on my notion page (even holding Ctrl), the page will open in a new Electron window instead of my usual browser (Firefox).

**Comment by Pietrucci-Blacher** [comment]
Hello again, I've just tested to reproduce it, no problem observing even changing default browsers several times (Chrome, Firefox, Brave), the link opens fine outside the Electron application. Once again, I'm going to close this issue and will keep you informed if any problems arise in connection with this ticket ;)
